Stjornutextar/Models/Subtitle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Stjornutextar.Models
{
	public class UrlType : ValidationAttribute
	{
		public override bool IsValid(object value)
		{
			// don't duplicate the required validator - return true
			if (value == null)
			{
				return true;
			}

			// is the file extention correct?
			//var postedFileName = ((HttpPostedFileBase)value).FileName.ToLower();
			string temp = value.ToString();
			
			if (temp.StartsWith("http://") != true && temp.StartsWith("https://") != true)
			{
				return false;
			}

			return true;
		}
	}
	
	public class Subtitle
	{
		public int ID { get; set; }
		[Required(ErrorMessage = "Title is required!")] // Verður að taka gildi, gefur annars villumeldingu
		public string Title { get; set; }
		public string Status { get; set; }
		[UrlType(ErrorMessage = "Vinsamlegast hafðu hlekkinn á eftirfarandi formi: http:/www.example.com/")] // Verður að hlaða inn .srt skrá
		public string MediaURL { get; set; }
		public DateTime PublishDate { get; set; }
		public int Votes { get; set; }
		public int countTranslations { get; set; }
		public string SubtitleFileText { get; set; }

		public Category Category { get; set; }
		public Language Language { get; set; }

		public List<SubtitlePart> SubtitleParts { get; set; }
	}
}

Stjornutextar/ViewModels/SubtitleViewModel.cs
using Stjornutextar.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Stjornutextar.ViewModels
{
	public class FileType : ValidationAttribute
	{
		private string _fileExtention;

		public FileType(string fileExtention)
		{
			_fileExtention = fileExtention;
		}

		public override bool IsValid(object value)
		{
			// don't duplicate the required validator - return true
			if (value == null)
			{
				return true;
			}

			// is the file extention correct?
			var postedFileName = ((HttpPostedFileBase)value).FileName.ToLower();

			if (postedFileName.Substring(postedFileName.LastIndexOf('.') + 1) != _fileExtention)
			{
				return false;
			}

			return true;
		}
	}
	
	public class SubtitleViewModel
	{
		public Subtitle Subtitle { get; set; }
		public List<Category> Categories { get; set; }
		public List<Language> Languages { get; set; }
		[Required]
		[FileType("srt", ErrorMessage = "Vinsamlegast settu inn .srt skrá.")] // Verður að hlaða inn .srt skrá
		public HttpPostedFileBase SubtitleFile { get; set; }
	}
}

Stjornutextar/Controllers/SubtitleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stjornutextar.Models;
using Stjornutextar.Repositories;
using System.IO;
using Stjornutextar.ViewModels;
using System.Text;

namespace Stjornutextar.Controllers
{
    [Authorize]
	public class SubtitleController : Controller
    {
		// Búum til tilvik af repository-inum okkar til að vinna með í gegnum föllin.
		SubtitleRepository subRepo = new SubtitleRepository();
		SubtitlePartRepository subPartRepo = new SubtitlePartRepository();

        // GET: /Subtitle/
		[AllowAnonymous]
        public ActionResult Index(string name, int? id)
        {
            SubtitleListViewModel subtitleLVM = new SubtitleListViewModel();
            subtitleLVM.Categories = subRepo.PopulateCategories();
            subtitleLVM.Languages = subRepo.PopulateLanguages();


            if (!String.IsNullOrEmpty(name))
            {
                subtitleLVM.Subtitles = subRepo.GetSubtitleByName(name);
                return View(subtitleLVM);
            }
            else if (id != null)
            {
                subtitleLVM.Subtitles = subRepo.GetSubtitlesByCategory(id);
                return View(subtitleLVM);
            }
            else 
            {
                subtitleLVM.Subtitles = subRepo.GetFirst10Subtitles();
                return View(subtitleLVM);
            }
           
        }

        // GET: /Subtitle/Create
        public ActionResult Create()
		{
			#region Búa til ViewModel og fylla inn í það flokka, tungumál og þýðingu
			SubtitleViewModel subtitleVM = new SubtitleViewModel();
			subtitleVM.Categories = subRepo.PopulateCategories();
			subtitleVM.Languages = subRepo.PopulateLanguages();
			#endregion

			return View(subtitleVM);
        }	

        // POST: /Subtitle/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
		public ActionResult Create(SubtitleViewModel subtitleVM)
        {
			subtitleVM.Categories = subRepo.PopulateCategories();
			subtitleVM.Languages = subRepo.PopulateLanguages();

			subtitleVM.Subtitle.PublishDate = DateTime.Now;
			subtitleVM.Subtitle.Status = "Óklárað";
			subtitleVM.Subtitle.Votes = 0;
			
			if (ModelState.IsValid)
			{
				#region Sækir tilvik af Category og Language og setur í ViewModel-ið
				subtitleVM.Subtitle.Category = subRepo.GetCategory(subtitleVM.Subtitle.Category.ID);
				subtitleVM.Subtitle.Language = subRepo.GetLanguage(subtitleVM.Subtitle.Language.ID);
				#endregion

				#region Viðbótarupplýsingar fyrir Subtitle sem kerfið setur sjálft
				//if(subtitleVM.UlSubtitleFile.ContentLength != 0)
				//{
					// Innihald skráar sett inn í SubtitleFileText breytu í Subtitle
					subtitleVM.Subtitle.SubtitleFileText = new StreamReader(subtitleVM.SubtitleFile.InputStream, Encoding.UTF8, false).ReadToEnd();
					// Búinn til listi af strengjum og SubtitleFileText splittað upp í strengja brot
					List<string> TempSubtitleParts = subtitleVM.Subtitle.SubtitleFileText.Split(new string[] { "\r\n\r\n" }, StringSplitOptions.None).ToList();
					// Listi sem inniheldur hvert þýðingarbrot splittað upp fyrir ID, tíma og texta
					List<List<string>> SubtitlePartsDivided = new List<List<string>>();

					foreach (var subtitlePart in TempSubtitleParts)
					{
						List<string> temp = new List<string>();

						foreach (var str in subtitlePart.Split(new string[] { "\r\n" }, StringSplitOptions.None).ToList())
						{
							temp.Add(str);
						}
						SubtitlePartsDivided.Add(temp);
					}
					SubtitlePartsDivided.RemoveAt(SubtitlePartsDivided.Count()-1);

					subtitleVM.Subtitle.SubtitleParts = new List<SubtitlePart>();
					// Færum innihald skjátextaskráar sem var hlaðið inn úr listum í model og vistum í gagnagrunni
					foreach (var subtitlePartDivided in SubtitlePartsDivided)
					{
						SubtitlePart subtitlePart = new SubtitlePart();

						for (int i = 0; i < subtitlePartDivided.Count(); i++)
						{
							if (i == 0)
							{
								if (subtitlePartDivided[i] != "")
									subtitlePart.partNumber = Convert.ToInt32(subtitlePartDivided[i]);
								else
									break;
							}
							else if (i == 1)
								subtitlePart.time = subtitlePartDivided[i];
							else if (i == 2)
								subtitlePart.text1 = subtitlePartDivided[i];
							else
								subtitlePart.text2 = subtitlePartDivided[i];
						}
						subtitlePart.SubtitleID = subtitleVM.Subtitle.ID;
						subtitleVM.Subtitle.SubtitleParts.Add(subtitlePart);
					}
				//}
				#endregion

				subRepo.AddSubtitle(subtitleVM.Subtitle);
                return RedirectToAction("Index");
            }

           return View(subtitleVM);
        }

        // GET: /Subtitle/Edit/5
        public ActionResult Edit(int id)
		{
			#region Búa til ViewModel og fylla inn í það flokka, tungumál og þýðingu
			SubtitleViewModel subtitleVM = new SubtitleViewModel();
			subtitleVM.Categories = subRepo.PopulateCategories();
			subtitleVM.Languages = subRepo.PopulateLanguages();
			subtitleVM.Subtitle = subRepo.GetSubtitleById(id);
			#endregion

			if (subtitleVM.Subtitle == null)
            {
                return HttpNotFound();
            }
            return View(subtitleVM);
        }

        // POST: /Subtitle/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
		public ActionResult Edit(SubtitleViewModel subtitleVM)
        {
			//if (ModelState.IsValid)
            //{
				#region Sækir tilvik af Category og Language og setur í ViewModel-ið
				subtitleVM.Subtitle.Category = subRepo.GetCategory(subtitleVM.Subtitle.Category.ID);
				subtitleVM.Subtitle.Language = subRepo.GetLanguage(subtitleVM.Subtitle.Language.ID);
				#endregion

				subRepo.UpdateSubtitle(subtitleVM.Subtitle);
                return RedirectToAction("Index");
           // }
//            return View(subtitleVM);
        }

		// GET: /Subtitle/Download/5
		[AllowAnonymous]
		public FileStreamResult CreateFile(int id)
		{
			Subtitle subtitle = subRepo.GetSubtitleById(id);
			List<SubtitlePart> subtitleParts = subPartRepo.GetAllSubtitlePartsById(id);
			
			string data = "";
			string tempData;

			for (int i = 0; i < subtitleParts.Count; i++) // Rúllar í gegnum alla SubtitleParta í listanum og skrifar bætir við í einn streng
			{
				if (subtitleParts[i].translatedText2 != null )
				{
					tempData = (subtitleParts[i].partNumber + "\r\n" + subtitleParts[i].time + "\r\n" + subtitleParts[i].translatedText1 + "\r\n" + subtitleParts[i].translatedText2 + "\r\n" + "\r\n");
					data = data + tempData;
				}
				else
				{
					tempData = (subtitleParts[i].partNumber + "\r\n" + subtitleParts[i].time + "\r\n" + subtitleParts[i].translatedText1 + "\r\n" + "\r\n");
					data = data + tempData;
				}
			}
			//todo: add some data from your database into that string:
			var string_with_your_data = data;

			var byteArray = Encoding.UTF8.GetBytes(string_with_your_data);
			var stream = new MemoryStream(byteArray);

			return File(stream, "text/plain", subtitle.Title + ".srt");
		}
    }
}

Stjornutextar/Controllers/SubtitlePartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stjornutextar.Models;
using Stjornutextar.Repositories;
using Stjornutextar.ViewModels;

namespace Stjornutextar.Controllers
{
    [Authorize]
	public class SubtitlePartController : Controller
    {
		// Búum til tilvik af repository-inum okkar til að vinna með í gegnum föllin.
		SubtitlePartRepository subPartRepo = new SubtitlePartRepository();
		SubtitleRepository subRepo = new SubtitleRepository();

        // GET: /SubtitlePart/
        public ActionResult Index(int id)
        {
			SubtitlePartListViewModel subPartLVM = new SubtitlePartListViewModel();
			subPartLVM.Subtitle = subRepo.GetSubtitleById(id);
			subPartLVM.Subtitle.MediaURL.Replace("watch?v=", "embed/");
			subPartLVM.SubtitleParts = subPartRepo.GetAllSubtitlePartsById(id);
			
			return View(subPartLVM);
        }

		// GET: /SubtitlePart/Edit/5
		public ActionResult Edit(int id)
		{
			SubtitlePart subtitlePart = subPartRepo.GetSubtitlePartById(id);
			if (subtitlePart == null)
			{
				return HttpNotFound();
			}
			return View(subtitlePart);
		}

		// POST: /SubtitlePart/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(SubtitlePart subtitlePart)
		{
			if (ModelState.IsValid)
			{
				subPartRepo.UpdateSubtitlePart(subtitlePart);
				Subtitle subtitle = subRepo.GetSubtitleById(subtitlePart.SubtitleID);
				subtitle.SubtitleParts = subPartRepo.GetAllSubtitlePartsById(subtitlePart.SubtitleID);
				subtitle.countTranslations++;

				if (subtitle.countTranslations == subtitle.SubtitleParts.Count)
					subtitle.Status = "Klárað";
				
				subRepo.ChangeSubtitleStatus(subtitle);

				return RedirectToAction("Index/" + subtitlePart.SubtitleID);
			}
			return View(subtitlePart);
		}
    }
}

Stjornutextar/Views/Subtitle/Create.cshtml
@model Stjornutextar.ViewModels.SubtitleViewModel

@{
    ViewBag.Title = "Stofna Þýðingu";
}

<h2>Stofna Þýðingu</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "subtitleForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.Label("Titill", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subtitle.Title)
                @Html.ValidationMessageFor(model => model.Subtitle.Title)
            </div>
        </div>   
    
        <div class="form-group">
            @Html.Label("Flokkur", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Subtitle.Category.ID, new SelectList(Model.Categories, "ID", "CategoryName"))
                @Html.ValidationMessageFor(model => model.Subtitle.Category)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tungumál", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Subtitle.Language.ID, new SelectList(Model.Languages, "ID", "LanguageName"))
                @Html.ValidationMessageFor(model => model.Subtitle.Language)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Hlekkur", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subtitle.MediaURL)
                @Html.ValidationMessageFor(model => model.Subtitle.MediaURL)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Skjátextaskrá", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="SubtitleFile" id="SubtitleFile" />
                @Html.ValidationMessageFor(model => model.SubtitleFile)
            </div>
        </div>

        <div class="form-group"> 
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Stofna þýðingu" class="btn btn-success" />
            </div>
        </div>
    </div>
}


<div>
    @Html.ActionLink("Til baka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Stjornutextar/Views/Subtitle/Edit.cshtml
@model Stjornutextar.ViewModels.SubtitleViewModel

@{
    ViewBag.Title = "Breyta";
}

<h2>Breyta skjátexta</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "subtitleForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Subtitle.ID)
        
        <div class="form-group">
            @Html.Label("Titill", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Subtitle.Title)
                @Html.ValidationMessageFor(model => model.Subtitle.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Flokkur", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Subtitle.Category.ID, new SelectList(Model.Categories, "ID", "CategoryName"))
                @Html.ValidationMessageFor(model => model.Subtitle.Category)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tungumál", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Subtitle.Language.ID, new SelectList(Model.Languages, "ID", "LanguageName"))
                @Html.ValidationMessageFor(model => model.Subtitle.Language)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Staða", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Subtitle.Status)
                @Html.ValidationMessageFor(model => model.Subtitle.Status)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Hlekkur á myndband", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subtitle.MediaURL)
                @Html.ValidationMessageFor(model => model.Subtitle.MediaURL)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Dagsetning", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               
                @Html.DisplayFor(model => model.Subtitle.PublishDate)
                @Html.ValidationMessageFor(model => model.Subtitle.PublishDate)
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Vista" class="btn btn-primary" />
                @Html.ActionLink("Þýða skjátexta", "index", "SubtitlePart", new { id = Model.Subtitle.ID }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Til baka", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Stjornutextar/Views/Subtitle/Index.cshtml
@model Stjornutextar.ViewModels.SubtitleListViewModel


@{
    ViewBag.Title = "Stjörnutextar";
    <div class="img_container">
        <img src="~/Content/Images/kings.jpg" alt="SubKings"/>
    </div>
}
   
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="textbox_container">
            @Html.TextBox("name")
            <input type="submit" value="Leita að þýðingu" class="btn-group-sm" />
        </div>
    }
    <div class="button_container">
        <div class="btn-group">
            <button class=" btn btn-primary">@Html.ActionLink("Kvikmyndir", "Index", new { id = Model.Categories[0].ID })</button>
            <button class="btn btn-primary">@Html.ActionLink("Þættir", "Index", new { id = Model.Categories[1].ID })</button>
            <button class="btn btn-primary">@Html.ActionLink("Heimildarmyndir", "Index", new { id = Model.Categories[2].ID })</button>
            <button class="btn btn-primary">@Html.ActionLink("Barnaefni", "Index", new { id = Model.Categories[3].ID })</button>
        </div>
    </div>
<div class="btn btn-success" style="float:right;">
    @Html.ActionLink("Stofna Þýðingu", "Create")
</div>
            
<table class="table">
    <tr>
        <th>
           Flokkur
        </th>
        <th>
           Titill
        </th>
        <th>
            Staða
        </th>
        <th>
            Hlekkur á myndband
        </th>
        <th>
            Sækja skrá
        </th>
        <th>
            Stofnað
        </th>
        <th>
            Tungumál
        </th>
        <th>
            Líka við
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Subtitles) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a class="glyphicon glyphicon-facetime-video" href="@item.MediaURL"></a></td>
            <td>
                <a class="glyphicon glyphicon-download-alt" href=@Url.Action("CreateFile/" + item.ID)> </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishDate)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Language.LanguageName)
            </td>
            <td>
                <a class="glyphicon glyphicon-thumbs-up" href=@Url.Action("Create")> </a>
            </td>
            <td>
                @Html.ActionLink("Breyta", "Edit", new { id=item.ID })
            </td>
        </tr>
    }
</table>