Stjornutextar/Models/SubtitlePart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stjornutextar.Models
{
	public class SubtitlePart
	{
		public int ID { get; set; }
		public int partNumber { get; set; }
		public string time { get; set; }
		public string text1 { get; set; }
		public string text2 { get; set; }
		public string translatedText1 { get; set; }
		public string translatedText2 { get; set; }

		public int SubtitleID { get; set; }
		public Subtitle Subtitle { get; set; }
	}
}

Stjornutextar/Controllers/SubtitleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stjornutextar.Models;
using Stjornutextar.Repositories;
using System.IO;
using Stjornutextar.ViewModels;
using System.Text;

namespace Stjornutextar.Controllers
{
    [Authorize]
	public class SubtitleController : Controller
    {
		// Búum til tilvik af repository-inum okkar til að vinna með í gegnum föllin.
		SubtitleRepository subRepo = new SubtitleRepository();
		SubtitlePartRepository subPartRepo = new SubtitlePartRepository();

        // GET: /Subtitle/
		[AllowAnonymous]
        public ActionResult Index(string name, int? id)
        {
            SubtitleListViewModel subtitleLVM = new SubtitleListViewModel();
            subtitleLVM.Categories = subRepo.PopulateCategories();
            subtitleLVM.Languages = subRepo.PopulateLanguages();


            if (!String.IsNullOrEmpty(name))
            {
                subtitleLVM.Subtitles = subRepo.GetSubtitleByName(name);
                return View(subtitleLVM);
            }
            else if (id != null)
            {
                subtitleLVM.Subtitles = subRepo.GetSubtitlesByCategory(id);
                return View(subtitleLVM);
            }
            else 
            {
                subtitleLVM.Subtitles = subRepo.GetFirst10Subtitles();
                return View(subtitleLVM);
            }
           
        }

        // GET: /Subtitle/Create
        public ActionResult Create()
		{
			#region Búa til ViewModel og fylla inn í það flokka, tungumál og þýðingu
			SubtitleViewModel subtitleVM = new SubtitleViewModel();
			subtitleVM.Categories = subRepo.PopulateCategories();
			subtitleVM.Languages = subRepo.PopulateLanguages();
			#endregion

			return View(subtitleVM);
        }	

        // POST: /Subtitle/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
		public ActionResult Create(SubtitleViewModel subtitleVM)
        {
			subtitleVM.Categories = subRepo.PopulateCategories();
			subtitleVM.Languages = subRepo.PopulateLanguages();

			subtitleVM.Subtitle.PublishDate = DateTime.Now;
			subtitleVM.Subtitle.Status = "Óklárað";
			subtitleVM.Subtitle.Votes = 0;
			
			if (ModelState.IsValid)
			{
				#region Sækir tilvik af Category og Language og setur í ViewModel-ið
				subtitleVM.Subtitle.Category = subRepo.GetCategory(subtitleVM.Subtitle.Category.ID);
				subtitleVM.Subtitle.Language = subRepo.GetLanguage(subtitleVM.Subtitle.Language.ID);
				#endregion

				#region Viðbótarupplýsingar fyrir Subtitle sem kerfið setur sjálft
				//if(subtitleVM.UlSubtitleFile.ContentLength != 0)
				//{
					// Innihald skráar sett inn í SubtitleFileText breytu í Subtitle
					subtitleVM.Subtitle.SubtitleFileText = new StreamReader(subtitleVM.SubtitleFile.InputStream, Encoding.UTF8, false).ReadToEnd();
					// Búinn til listi af strengjum og SubtitleFileText splittað upp í strengja brot
					List<string> TempSubtitleParts = subtitleVM.Subtitle.SubtitleFileText.Split(new string[] { "\r\n\r\n" }, StringSplitOptions.None).ToList();
					// Listi sem inniheldur hvert þýðingarbrot splittað upp fyrir ID, tíma og texta
					List<List<string>> SubtitlePartsDivided = new List<List<string>>();

					foreach (var subtitlePart in TempSubtitleParts)
					{
						List<string> temp = new List<string>();

						foreach (var str in subtitlePart.Split(new string[] { "\r\n" }, StringSplitOptions.None).ToList())
						{
							temp.Add(str);
						}
						SubtitlePartsDivided.Add(temp);
					}
					SubtitlePartsDivided.RemoveAt(SubtitlePartsDivided.Count()-1);

					subtitleVM.Subtitle.SubtitleParts = new List<SubtitlePart>();
					// Færum innihald skjátextaskráar sem var hlaðið inn úr listum í model og vistum í gagnagrunni
					foreach (var subtitlePartDivided in SubtitlePartsDivided)
					{
						SubtitlePart subtitlePart = new SubtitlePart();

						for (int i = 0; i < subtitlePartDivided.Count(); i++)
						{
							if (i == 0)
							{
								if (subtitlePartDivided[i] != "")
									subtitlePart.partNumber = Convert.ToInt32(subtitlePartDivided[i]);
								else
									break;
							}
							else if (i == 1)
								subtitlePart.time = subtitlePartDivided[i];
							else if (i == 2)
								subtitlePart.text1 = subtitlePartDivided[i];
							else
								subtitlePart.text2 = subtitlePartDivided[i];
						}
						subtitlePart.SubtitleID = subtitleVM.Subtitle.ID;
						subtitleVM.Subtitle.SubtitleParts.Add(subtitlePart);
					}
				//}
				#endregion

				subRepo.AddSubtitle(subtitleVM.Subtitle);
                return RedirectToAction("Index");
            }

           return View(subtitleVM);
        }

        // GET: /Subtitle/Edit/5
        public ActionResult Edit(int id)
		{
			#region Búa til ViewModel og fylla inn í það flokka, tungumál og þýðingu
			SubtitleViewModel subtitleVM = new SubtitleViewModel();
			subtitleVM.Categories = subRepo.PopulateCategories();
			subtitleVM.Languages = subRepo.PopulateLanguages();
			subtitleVM.Subtitle = subRepo.GetSubtitleById(id);
			#endregion

			if (subtitleVM.Subtitle == null)
            {
                return HttpNotFound();
            }
            return View(subtitleVM);
        }

        // POST: /Subtitle/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
		public ActionResult Edit(SubtitleViewModel subtitleVM)
        {
			//if (ModelState.IsValid)
            //{
				#region Sækir tilvik af Category og Language og setur í ViewModel-ið
				subtitleVM.Subtitle.Category = subRepo.GetCategory(subtitleVM.Subtitle.Category.ID);
				subtitleVM.Subtitle.Language = subRepo.GetLanguage(subtitleVM.Subtitle.Language.ID);
				#endregion

				subRepo.UpdateSubtitle(subtitleVM.Subtitle);
                return RedirectToAction("Index");
           // }
//            return View(subtitleVM);
        }

		// GET: /Subtitle/Download/5
		[AllowAnonymous]
		public FileStreamResult CreateFile(int id)
		{
			Subtitle subtitle = subRepo.GetSubtitleById(id);
			List<SubtitlePart> subtitleParts = subPartRepo.GetAllSubtitlePartsById(id);
			
			string data = "";
			string tempData;

			for (int i = 0; i < subtitleParts.Count; i++) // Rúllar í gegnum alla SubtitleParta í listanum og skrifar bætir við í einn streng
			{
				if (subtitleParts[i].translatedText2 != null )
				{
					tempData = (subtitleParts[i].partNumber + "\r\n" + subtitleParts[i].time + "\r\n" + subtitleParts[i].translatedText1 + "\r\n" + subtitleParts[i].translatedText2 + "\r\n" + "\r\n");
					data = data + tempData;
				}
				else
				{
					tempData = (subtitleParts[i].partNumber + "\r\n" + subtitleParts[i].time + "\r\n" + subtitleParts[i].translatedText1 + "\r\n" + "\r\n");
					data = data + tempData;
				}
			}
			//todo: add some data from your database into that string:
			var string_with_your_data = data;

			var byteArray = Encoding.UTF8.GetBytes(string_with_your_data);
			var stream = new MemoryStream(byteArray);

			return File(stream, "text/plain", subtitle.Title + ".srt");
		}
    }
}

Stjornutextar/Controllers/SubtitlePartController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stjornutextar.Models;
using Stjornutextar.Repositories;
using Stjornutextar.ViewModels;

namespace Stjornutextar.Controllers
{
    [Authorize]
	public class SubtitlePartController : Controller
    {
		// Búum til tilvik af repository-inum okkar til að vinna með í gegnum föllin.
		SubtitlePartRepository subPartRepo = new SubtitlePartRepository();
		SubtitleRepository subRepo = new SubtitleRepository();

        // GET: /SubtitlePart/
        public ActionResult Index(int id)
        {
			SubtitlePartListViewModel subPartLVM = new SubtitlePartListViewModel();
			subPartLVM.Subtitle = subRepo.GetSubtitleById(id);
			subPartLVM.Subtitle.MediaURL.Replace("watch?v=", "embed/");
			subPartLVM.SubtitleParts = subPartRepo.GetAllSubtitlePartsById(id);
			
			return View(subPartLVM);
        }

		// GET: /SubtitlePart/Edit/5
		public ActionResult Edit(int id)
		{
			SubtitlePart subtitlePart = subPartRepo.GetSubtitlePartById(id);
			if (subtitlePart == null)
			{
				return HttpNotFound();
			}
			return View(subtitlePart);
		}

		// POST: /SubtitlePart/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(SubtitlePart subtitlePart)
		{
			if (ModelState.IsValid)
			{
				subPartRepo.UpdateSubtitlePart(subtitlePart);
				Subtitle subtitle = subRepo.GetSubtitleById(subtitlePart.SubtitleID);
				subtitle.SubtitleParts = subPartRepo.GetAllSubtitlePartsById(subtitlePart.SubtitleID);
				subtitle.countTranslations++;

				if (subtitle.countTranslations == subtitle.SubtitleParts.Count)
					subtitle.Status = "Klárað";
				
				subRepo.ChangeSubtitleStatus(subtitle);

				return RedirectToAction("Index/" + subtitlePart.SubtitleID);
			}
			return View(subtitlePart);
		}
    }
}

Stjornutextar/Views/SubtitlePart/Create.cshtml
@model Stjornutextar.Models.SubtitlePart

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubtitlePart</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.partNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.partNumber)
                @Html.ValidationMessageFor(model => model.partNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time)
                @Html.ValidationMessageFor(model => model.time)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text1)
                @Html.ValidationMessageFor(model => model.text1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text2)
                @Html.ValidationMessageFor(model => model.text2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.translatedText1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.translatedText1)
                @Html.ValidationMessageFor(model => model.translatedText1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.translatedText2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.translatedText2)
                @Html.ValidationMessageFor(model => model.translatedText2)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Stjornutextar/Views/SubtitlePart/Delete.cshtml
@model Stjornutextar.Models.SubtitlePart

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SubtitlePart</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.partNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.partNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.translatedText1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.translatedText1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.translatedText2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.translatedText2)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Stjornutextar/Views/SubtitlePart/Details.cshtml
@model Stjornutextar.Models.SubtitlePart

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SubtitlePart</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.partNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.partNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.translatedText1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.translatedText1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.translatedText2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.translatedText2)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Stjornutextar/Views/SubtitlePart/Edit.cshtml
@model Stjornutextar.Models.SubtitlePart

@{
    ViewBag.Title = "Þýða skjátexta brot";
}

<h2>Þýða skjátexta brot:</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Brot númer @Model.partNumber</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.time, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.time)
                @Html.ValidationMessageFor(model => model.time)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.text1)
                @Html.ValidationMessageFor(model => model.text1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.text2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.text2)
                @Html.ValidationMessageFor(model => model.text2)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.translatedText1, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.translatedText1)
                @Html.ValidationMessageFor(model => model.translatedText1)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.translatedText2, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.translatedText2)
                @Html.ValidationMessageFor(model => model.translatedText2)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Vista" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Til baka í lista", "Index/" + @Model.SubtitleID)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Stjornutextar/Views/SubtitlePart/Index.cshtml
@model Stjornutextar.ViewModels.SubtitlePartListViewModel

@{
    ViewBag.Title = "Listi yfir öll skjátexta brot";
}

<h2>Skjátextabrot fyrir @Model.Subtitle.Title</h2>

<div class="col-lg-offset-3">
    <iframe width="560" height="315" src="@Model.Subtitle.MediaURL.Replace("watch?v=", "embed/")" frameborder="1"></iframe>
</div>

<table class="table">
    <tr>
        <th>
            Númer
        </th>
        <th>
            Tími
        </th>
        <th>
            Texti 1
        </th>
        <th>
            Texti 2
        </th>
        <th>
            Þýðing 1
        </th>
        <th>
            Þýðing 2
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.SubtitleParts) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.partNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.text1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.text2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.translatedText1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.translatedText2)
        </td>
        <td>
            @Html.ActionLink("Þýða", "Edit", new { id=item.ID })
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Til baka í lista", "Index", "Subtitle")
</div>